name : test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-lastest

    strategy:
      matrix:
        node-version: [18]

    steps:
    - uses: actions/checkout@v4

    - names: Use Node.js ${{ matrix.node-version }}
      uses: action/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - names: Build
      run: |
        npm install
        npm run start
      
      
      
